/**
 * 跨模块只读查找：各岗位模板都含 dashboard，不再按模块重复罗列权限。
 * 写接口仍走各自业务权限。
 */
const LOOKUP_READ_PERMISSIONS = Object.freeze(['dashboard']);

module.exports = {
  LOOKUP_READ_PERMISSIONS,
  USER_OPTION_PERMISSIONS: LOOKUP_READ_PERMISSIONS,
  DEPARTMENT_OPTION_PERMISSIONS: LOOKUP_READ_PERMISSIONS,
  FINANCE_BUSINESS_OPTION_PERMISSIONS: LOOKUP_READ_PERMISSIONS,
  SUPPLEMENT_REASON_PERMISSIONS: LOOKUP_READ_PERMISSIONS,
};
