#!/usr/bin/env node

/**
 * Offline disaster-recovery restore for SQL files generated by BackupService.
 * The target database must already exist and be empty. A checksum and an exact
 * database-name confirmation are mandatory to prevent accidental overwrites.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');
const mysql = require('mysql2/promise');
const { isEncryptedBackup, decryptFile } = require('../src/utils/backupCrypto');
require('dotenv').config();

function parseArguments(argv) {
  const args = {};
  for (const token of argv) {
    if (token === '--help' || token === '-h') args.help = true;
    else if (token.startsWith('--') && token.includes('=')) {
      const separator = token.indexOf('=');
      args[token.slice(2, separator)] = token.slice(separator + 1);
    }
  }
  return args;
}

function usage() {
  return [
    'Usage:',
    '  npm run restore:offline -- --file=/path/backup.sql[.enc] --database=erp_restore --confirm=erp_restore',
    '',
    'Requirements:',
    '  - The target database must already exist and contain no base tables.',
    '  - backup.sql[.enc].sha256 must exist, or pass --checksum=<64 hex characters>.',
    '  - DB_HOST, DB_PORT, DB_USER and DB_PASSWORD must be configured.',
  ].join('\n');
}

async function sha256File(filePath) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    const stream = fs.createReadStream(filePath);
    stream.on('data', (chunk) => hash.update(chunk));
    stream.on('end', () => resolve(hash.digest('hex')));
    stream.on('error', reject);
  });
}

async function expectedChecksum(filePath, explicitChecksum) {
  if (explicitChecksum) return explicitChecksum.trim().toLowerCase();
  const sidecar = await fs.promises.readFile(`${filePath}.sha256`, 'utf8');
  return sidecar.trim().split(/\s+/)[0].toLowerCase();
}

async function inspectBackup(filePath) {
  const input = fs.createReadStream(filePath, { encoding: 'utf8' });
  const lines = readline.createInterface({ input, crlfDelay: Infinity });
  let hasForeignKeyOff = false;
  let hasForeignKeyOn = false;
  let tableCount = 0;

  for await (const line of lines) {
    hasForeignKeyOff ||= /SET\s+FOREIGN_KEY_CHECKS\s*=\s*0/i.test(line);
    hasForeignKeyOn ||= /SET\s+FOREIGN_KEY_CHECKS\s*=\s*1/i.test(line);
    if (/^CREATE\s+TABLE/i.test(line.trim())) tableCount += 1;
  }

  if (!hasForeignKeyOff || !hasForeignKeyOn || tableCount === 0) {
    throw new Error('Backup preflight failed: required restore guards or table definitions are missing');
  }
  return { tableCount };
}

async function restoreStatements(connection, filePath) {
  const input = fs.createReadStream(filePath, { encoding: 'utf8' });
  const lines = readline.createInterface({ input, crlfDelay: Infinity });
  let statement = '';
  let statementCount = 0;

  for await (const line of lines) {
    const trimmed = line.trim();
    if (!statement && (!trimmed || trimmed.startsWith('--'))) continue;
    statement += `${line}\n`;
    if (!trimmed.endsWith(';')) continue;

    try {
      await connection.query(statement);
    } catch (error) {
      const objectMatch = statement.match(
        /(?:INSERT\s+INTO|CREATE\s+TABLE|DROP\s+TABLE\s+IF\s+EXISTS)\s+(`[^`]+`|[A-Za-z0-9_]+)/i
      );
      const objectName = objectMatch ? objectMatch[1] : 'unknown object';
      throw new Error(`Statement ${statementCount + 1} failed for ${objectName}: ${error.message}`, {
        cause: error,
      });
    }
    statement = '';
    statementCount += 1;
  }

  if (statement.trim()) throw new Error('Backup contains an unterminated SQL statement');
  return statementCount;
}

async function main() {
  const args = parseArguments(process.argv.slice(2));
  if (args.help) {
    console.log(usage());
    return;
  }

  const filePath = path.resolve(args.file || '');
  const database = String(args.database || '');
  if (!args.file || !database || args.confirm !== database) {
    throw new Error(`Missing required arguments or confirmation mismatch.\n${usage()}`);
  }
  if (!/^[A-Za-z0-9_]+$/.test(database)) throw new Error('Invalid target database name');
  if (!/\.sql(?:\.enc)?$/i.test(filePath)) throw new Error('Backup file must use the .sql or .sql.enc extension');

  await fs.promises.access(filePath, fs.constants.R_OK);
  const expected = await expectedChecksum(filePath, args.checksum);
  if (!/^[a-f0-9]{64}$/.test(expected)) throw new Error('Invalid SHA-256 checksum');
  const actual = await sha256File(filePath);
  if (actual !== expected) throw new Error('Backup checksum mismatch');
  let restorePath = filePath;
  let temporaryPlainPath = null;
  if (await isEncryptedBackup(filePath)) {
    temporaryPlainPath = path.join(path.dirname(filePath), `.restore_${crypto.randomUUID()}.sql`);
    await decryptFile(filePath, temporaryPlainPath);
    restorePath = temporaryPlainPath;
  }
  const preflight = await inspectBackup(restorePath);

  const connection = await mysql.createConnection({
    host: process.env.DB_HOST,
    port: Number(process.env.DB_PORT) || 3306,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database,
    charset: 'utf8mb4',
    multipleStatements: false,
  });

  try {
    const [[{ table_count: tableCount }]] = await connection.query(
      `SELECT COUNT(*) AS table_count
       FROM information_schema.tables
       WHERE table_schema = ? AND table_type = 'BASE TABLE'`,
      [database]
    );
    if (Number(tableCount) !== 0) {
      throw new Error(`Refusing to restore into non-empty database ${database}`);
    }

    const statementCount = await restoreStatements(connection, restorePath);
    const [[{ restored_tables: restoredTables }]] = await connection.query(
      `SELECT COUNT(*) AS restored_tables
       FROM information_schema.tables
       WHERE table_schema = ? AND table_type = 'BASE TABLE'`,
      [database]
    );
    if (Number(restoredTables) < preflight.tableCount) {
      throw new Error('Restore validation failed: restored table count is lower than the backup manifest');
    }

    console.log(JSON.stringify({
      restored: true,
      database,
      checksum: actual,
      statements: statementCount,
      tables: Number(restoredTables),
    }, null, 2));
  } finally {
    try {
      await connection.query('SET FOREIGN_KEY_CHECKS=1');
    } finally {
      await connection.end();
    }
    if (temporaryPlainPath) {
      await fs.promises.rm(temporaryPlainPath, { force: true }).catch(() => {});
    }
  }
}

main().catch((error) => {
  console.error(`Restore failed: ${error.message}`);
  process.exitCode = 1;
});
