async function columnExists(knex, tableName, columnName) {
  const [rows] = await knex.raw(
    `SELECT COUNT(*) AS count
     FROM information_schema.columns
     WHERE table_schema = DATABASE()
       AND table_name = ?
       AND column_name = ?`,
    [tableName, columnName]
  );
  return Number(rows[0].count) > 0;
}

async function tableExists(knex, tableName) {
  const [rows] = await knex.raw(
    `SELECT COUNT(*) AS count
     FROM information_schema.tables
     WHERE table_schema = DATABASE()
       AND table_name = ?`,
    [tableName]
  );
  return Number(rows[0].count) > 0;
}

async function addColumnIfMissing(knex, tableName, columnName, definition) {
  if (!(await columnExists(knex, tableName, columnName))) {
    await knex.raw(`ALTER TABLE \`${tableName}\` ADD COLUMN ${definition}`);
  }
}

async function accountExists(knex, accountCode) {
  const [rows] = await knex.raw(
    'SELECT COUNT(*) AS count FROM gl_accounts WHERE account_code = ?',
    [accountCode]
  );
  return Number(rows[0].count) > 0;
}

exports.up = async function up(knex) {
  if (!(await tableExists(knex, 'asset_impairments'))) {
    await knex.raw(`
      CREATE TABLE asset_impairments (
        id INT AUTO_INCREMENT PRIMARY KEY,
        asset_id INT NOT NULL,
        impairment_date DATE NOT NULL,
        impairment_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
        reason TEXT NULL,
        handled_by VARCHAR(100) NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_asset_impairments_asset_id (asset_id),
        INDEX idx_asset_impairments_date (impairment_date),
        CONSTRAINT fk_asset_impairments_asset
          FOREIGN KEY (asset_id) REFERENCES fixed_assets(id) ON DELETE RESTRICT
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='固定资产减值记录'
    `);
  }

  await addColumnIfMissing(
    knex,
    'asset_impairments',
    'gl_entry_id',
    'gl_entry_id INT NULL COMMENT "GL entry generated by asset impairment" AFTER created_at'
  );

  await addColumnIfMissing(
    knex,
    'asset_impairments',
    'voucher_no',
    'voucher_no VARCHAR(50) NULL COMMENT "Voucher/document number generated by asset impairment" AFTER gl_entry_id'
  );

  if (!(await accountExists(knex, '6702'))) {
    await knex('gl_accounts').insert({
      account_code: '6702',
      account_name: '\u8d44\u4ea7\u51cf\u503c\u635f\u5931',
      account_type: '\u8d39\u7528',
      type: 'expense',
      is_debit: 1,
      is_active: 1,
      currency_code: 'CNY',
      description: 'Default account for fixed asset impairment loss entries',
    });
  }
};

exports.down = async function down(knex) {
  if (await columnExists(knex, 'asset_impairments', 'voucher_no')) {
    await knex.raw('ALTER TABLE `asset_impairments` DROP COLUMN `voucher_no`');
  }

  if (await columnExists(knex, 'asset_impairments', 'gl_entry_id')) {
    await knex.raw('ALTER TABLE `asset_impairments` DROP COLUMN `gl_entry_id`');
  }

  const [usage] = await knex.raw(
    `SELECT COUNT(*) AS count
     FROM gl_entry_items item
     JOIN gl_accounts account ON account.id = item.account_id
     WHERE account.account_code = '6702'`
  );

  if (Number(usage[0].count) === 0) {
    await knex('gl_accounts')
      .where({ account_code: '6702', account_name: '\u8d44\u4ea7\u51cf\u503c\u635f\u5931' })
      .del();
  }
};
