/**
 * 财务管理 - 菜单权限数据
 * 从 menuPermissions.js 拆分
 */

export const financePerms = [
// 7. 财务管理
  {
    id: 7,
    parentId: 0,
    name: '财务管理',
    path: '/finance',
    component: '',
    icon: 'icon-money',
    type: 0,
    permission: 'finance',
    sort: 7,
    status: 1
  },
  // 总账管理
  {
    id: 71,
    parentId: 7,
    name: '会计科目',
    path: '/finance/gl/accounts',
    component: 'finance/gl/Accounts',
    icon: 'icon-account',
    type: 1,
    permission: 'finance:accounts:view',
    sort: 1,
    status: 1
  },
  {
    id: 7111,
    parentId: 7,
    name: '期初余额',
    path: '/finance/gl/opening-balances',
    component: 'finance/gl/OpeningBalances',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:accounts:view',
    sort: 2,
    status: 1
  },
  {
    id: 72,
    parentId: 7,
    name: '会计凭证',
    path: '/finance/gl/entries',
    component: '',
    icon: 'icon-document',
    type: 0, // 目录
    permission: 'finance:entries:view',
    sort: 3,
    status: 1
  },
  // 凭证子菜单
  {
    id: 721,
    parentId: 72,
    name: '凭证列表',
    path: '/finance/gl/entries',
    component: 'finance/gl/Entries',
    icon: 'icon-list',
    type: 1,
    permission: 'finance:entries:view',
    sort: 1,
    status: 1
  },
  {
    id: 722,
    parentId: 72,
    name: '收款凭证',
    path: '/finance/gl/entries/receipt',
    component: 'finance/gl/entries/ReceiptEntry',
    icon: 'icon-download',
    type: 1,
    permission: 'finance:entries:view',
    sort: 2,
    status: 1
  },
  {
    id: 723,
    parentId: 72,
    name: '付款凭证',
    path: '/finance/gl/entries/payment',
    component: 'finance/gl/entries/PaymentEntry',
    icon: 'icon-upload',
    type: 1,
    permission: 'finance:entries:view',
    sort: 4,
    status: 1
  },
  {
    id: 724,
    parentId: 72,
    name: '转账凭证',
    path: '/finance/gl/entries/transfer',
    component: 'finance/gl/entries/TransferEntry',
    icon: 'icon-right',
    type: 1,
    permission: 'finance:entries:view',
    sort: 4,
    status: 1
  },
  {
    id: 725,
    parentId: 72,
    name: '记账凭证',
    path: '/finance/gl/entries/general',
    component: 'finance/gl/entries/GeneralEntry',
    icon: 'icon-edit-outline',
    type: 1,
    permission: 'finance:entries:view',
    sort: 5,
    status: 1
  },
  {
    id: 73,
    parentId: 7,
    name: '会计期间',
    path: '/finance/gl/periods',
    component: 'finance/gl/Periods',
    icon: 'icon-calendar',
    type: 1,
    permission: 'finance:periods:view',
    sort: 3,
    status: 1
  },
  {
    id: 731,
    parentId: 7,
    name: '试算平衡表',
    path: '/finance/gl/trial-balance',
    component: 'finance/gl/TrialBalance',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:reports:view',
    sort: 31,
    status: 1
  },
  {
    id: 732,
    parentId: 7,
    name: '期间结账',
    path: '/finance/gl/period-closing',
    component: 'finance/gl/PeriodClosing',
    icon: 'icon-check',
    type: 1,
    permission: 'finance:closing:view',
    sort: 32,
    status: 1
  },
  // 应收账款
  {
    id: 74,
    parentId: 7,
    name: '销售发票',
    path: '/finance/ar/invoices',
    component: 'finance/ar/Invoices',
    icon: 'icon-tickets',
    type: 1,
    permission: 'finance:ar:view',
    sort: 4,
    status: 1
  },
  {
    id: 75,
    parentId: 7,
    name: '收款记录',
    path: '/finance/ar/receipts',
    component: 'finance/ar/Receipts',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:ar:view',
    sort: 5,
    status: 1
  },
  {
    id: 76,
    parentId: 7,
    name: '应收账龄',
    path: '/finance/ar/aging',
    component: 'finance/ar/Aging',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:reports:view',
    sort: 6,
    status: 1
  },
  // 应付账款
  {
    id: 77,
    parentId: 7,
    name: '采购发票',
    path: '/finance/ap/invoices',
    component: 'finance/ap/Invoices',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:ap:view',
    sort: 7,
    status: 1
  },
  {
    id: 78,
    parentId: 7,
    name: '付款记录',
    path: '/finance/ap/payments',
    component: 'finance/ap/Payments',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:ap:view',
    sort: 8,
    status: 1
  },
  {
    id: 79,
    parentId: 7,
    name: '应付账龄',
    path: '/finance/ap/aging',
    component: 'finance/ap/Aging',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:reports:view',
    sort: 9,
    status: 1
  },
  // 固定资产
  {
    id: 710,
    parentId: 7,
    name: '固定资产',
    path: '/finance/assets/list',
    component: 'finance/assets/AssetsList',
    icon: 'icon-goods',
    type: 1,
    permission: 'finance:assets:view',
    sort: 10,
    status: 1
  },
  {
    id: 711,
    parentId: 7,
    name: '资产类别',
    path: '/finance/assets/categories',
    component: 'finance/assets/AssetCategoryList',
    icon: 'icon-folder',
    type: 1,
    permission: 'finance:assets:view',
    sort: 11,
    status: 1
  },
  {
    id: 712,
    parentId: 7,
    name: '产品定价',
    path: '/finance/pricing',
    component: 'finance/pricing/ProductPricing',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:pricing:view',
    sort: 14,
    status: 1
  },
  {
    id: 713,
    parentId: 7,
    name: '折旧管理',
    path: '/finance/assets/depreciation',
    component: 'finance/assets/Depreciation',
    icon: 'icon-calendar',
    type: 1,
    permission: 'finance:assets:view',
    sort: 12,
    status: 1
  },
  {
    id: 7131,
    parentId: 7,
    name: '在建工程',
    path: '/finance/assets/cip',
    component: 'finance/assets/CIPList',
    icon: 'icon-office-building',
    type: 1,
    permission: 'finance:assets:view',
    sort: 13,
    status: 1
  },
  {
    id: 7132,
    parentId: 7,
    name: '资产盘点',
    path: '/finance/assets/inventory',
    component: 'finance/assets/AssetInventory',
    icon: 'icon-check',
    type: 1,
    permission: 'finance:assets:view',
    sort: 14,
    status: 1
  },
  {
    id: 7133,
    parentId: 7,
    name: '资产看板',
    path: '/finance/assets/reports',
    component: 'finance/assets/AssetReports',
    icon: 'icon-data-board',
    type: 1,
    permission: 'finance:assets:view',
    sort: 15,
    status: 1
  },
  // 出纳管理
  {
    id: 720,
    parentId: 7,
    name: '出纳管理',
    path: '/finance/cash',
    component: '',
    icon: 'icon-wallet',
    type: 0,
    permission: 'finance:cash:view',
    sort: 13,
    status: 1
  },
  {
    id: 7201,
    parentId: 720,
    name: '银行账户',
    path: '/finance/cash/accounts',
    component: 'finance/cash/BankAccounts',
    icon: 'icon-wallet',
    type: 1,
    permission: 'finance:cash:view',
    sort: 1,
    status: 1
  },
  {
    id: 7202,
    parentId: 720,
    name: '银行交易',
    path: '/finance/cash/bank-transactions',
    component: 'finance/cash/Transactions',
    icon: 'icon-right',
    type: 1,
    permission: 'finance:cash:view',
    sort: 2,
    status: 1
  },
  {
    id: 7203,
    parentId: 720,
    name: '现金交易',
    path: '/finance/cash/cash-transactions',
    component: 'finance/cash/CashTransactions',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:cash:view',
    sort: 3,
    status: 1
  },
  {
    id: 7204,
    parentId: 720,
    name: '银行对账',
    path: '/finance/cash/reconciliation',
    component: 'finance/cash/Reconciliation',
    icon: 'icon-check',
    type: 1,
    permission: 'finance:cash:reconcile',
    sort: 4,
    status: 1
  },
  {
    id: 7205,
    parentId: 720,
    name: '出纳报表',
    path: '/finance/reports/cash-flow',
    component: 'finance/reports/CashFlow',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:reports:view',
    sort: 5,
    status: 1
  },
  // 财务报表
  {
    id: 716,
    parentId: 7,
    name: '资产负债表',
    path: '/finance/reports/balance-sheet',
    component: 'finance/reports/BalanceSheet',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:reports:view',
    sort: 14,
    status: 1
  },
  {
    id: 717,
    parentId: 7,
    name: '利润表',
    path: '/finance/reports/income-statement',
    component: 'finance/reports/IncomeStatement',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:reports:view',
    sort: 15,
    status: 1
  },
  {
    id: 718,
    parentId: 7,
    name: '现金流量表',
    path: '/finance/reports/standard-cash-flow',
    component: 'finance/reports/StandardCashFlow',
    icon: 'icon-data-line',
    type: 1,
    permission: 'finance:reports:standard-cash-flow:view',
    sort: 16,
    status: 1
  },
  // 财务自动化
  {
    id: 719,
    parentId: 7,
    name: '财务自动化',
    path: '/finance/automation',
    component: 'finance/automation/FinanceAutomation',
    icon: 'icon-robot',
    type: 1,
    permission: 'finance:automation:view',
    sort: 16,
    status: 1
  },
  {
    id: 71901,
    parentId: 719,
    name: '执行',
    path: '',
    component: '',
    icon: '',
    type: 2,
    permission: 'finance:automation:execute',
    sort: 1,
    status: 1
  },
  {
    id: 7191,
    parentId: 7,
    name: '财务设置',
    path: '/finance/settings',
    component: 'finance/settings/FinanceSettings',
    icon: 'icon-setting',
    type: 1,
    permission: 'finance:settings:view',
    sort: 160,
    status: 1
  },
  {
    id: 7192,
    parentId: 7,
    name: '汇率维护',
    path: '/finance/settings/exchange-rates',
    component: 'finance/settings/ExchangeRates',
    icon: 'icon-coin',
    type: 1,
    permission: 'finance:exchange-rates:view',
    sort: 161,
    status: 1
  },
  // 税务管理
  {
    id: 730,
    parentId: 7,
    name: '税务管理',
    path: '/finance/tax',
    component: '',
    icon: 'icon-document',
    type: 0,
    permission: 'finance:tax:view',
    sort: 17,
    status: 1
  },
  {
    id: 7301,
    parentId: 730,
    name: '税务发票',
    path: '/finance/tax/invoices',
    component: 'finance/tax/TaxInvoices',
    icon: 'icon-tickets',
    type: 1,
    permission: 'finance:tax:view',
    sort: 1,
    status: 1
  },
  {
    id: 7302,
    parentId: 730,
    name: '税务申报',
    path: '/finance/tax/returns',
    component: 'finance/tax/TaxReturns',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:tax:view',
    sort: 2,
    status: 1
  },
  {
    id: 7303,
    parentId: 730,
    name: '税务科目配置',
    path: '/finance/tax/account-config',
    component: 'finance/tax/TaxAccountConfig',
    icon: 'icon-setting',
    type: 1,
    permission: 'finance:tax:view',
    sort: 3,
    status: 1
  },
  // 预算管理
  {
    id: 740,
    parentId: 7,
    name: '预算管理',
    path: '/finance/budget',
    component: '',
    icon: 'icon-data-analysis',
    type: 0,
    permission: 'finance:budgets:view',
    sort: 18,
    status: 1
  },
  {
    id: 741,
    parentId: 740,
    name: '预算列表',
    path: '/finance/budget/list',
    component: 'finance/budget/BudgetList',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:budgets:view',
    sort: 1,
    status: 1
  },
  {
    id: 742,
    parentId: 740,
    name: '新增预算',
    path: '/finance/budget/edit',
    component: 'finance/budget/BudgetEdit',
    icon: 'icon-edit',
    type: 1,
    permission: 'finance:budgets:create',
    sort: 2,
    visible: 0,
    status: 1
  },
  {
    id: 743,
    parentId: 740,
    name: '预算执行分析',
    path: '/finance/budget/execution',
    component: 'finance/budget/BudgetExecution',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:budgets:view',
    sort: 3,
    status: 1
  },
  {
    id: 744,
    parentId: 740,
    name: 'AI预算建议',
    path: '/finance/budget/ai',
    component: 'finance/budget/BudgetAI',
    icon: 'icon-cpu',
    type: 1,
    permission: 'finance:budgets:view',
    sort: 4,
    status: 1
  },

  // 成本管理
  {
    id: 750,
    parentId: 7,
    name: '成本管理',
    path: '/finance/cost',
    component: '',
    icon: 'icon-data-line',
    type: 0,
    permission: 'finance:cost:view',
    sort: 19,
    status: 1
  },
  {
    id: 751,
    parentId: 750,
    name: '成本驾驶舱',
    path: '/finance/cost/dashboard',
    component: 'finance/cost/CostDashboard',
    icon: 'icon-data-board',
    type: 1,
    permission: 'finance:cost:view',
    sort: 1,
    status: 1
  },
  {
    id: 753,
    parentId: 750,
    name: '标准成本',
    path: '/finance/cost/standard',
    component: 'finance/cost/StandardCost',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:cost:view',
    sort: 3,
    status: 1
  },
  {
    id: 7521,
    parentId: 750,
    name: '标准成本版本',
    path: '/finance/cost/versions',
    component: 'finance/cost/CostVersionManage',
    icon: 'icon-files',
    type: 1,
    permission: 'finance:cost:view',
    sort: 2,
    status: 1
  },
  {
    id: 7522,
    parentId: 750,
    name: '成本关账',
    path: '/finance/cost/closing',
    component: 'finance/cost/CostClosing',
    icon: 'icon-circle-check',
    type: 1,
    permission: 'finance:cost:view',
    sort: 3,
    status: 1
  },
  {
    id: 754,
    parentId: 750,
    name: '实际成本',
    path: '/finance/cost/actual',
    component: 'finance/cost/ActualCost',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:cost:view',
    sort: 4,
    status: 1
  },
  {
    id: 755,
    parentId: 750,
    name: '成本差异',
    path: '/finance/cost/variance',
    component: 'finance/cost/CostVariance',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:cost:view',
    sort: 5,
    status: 1
  },
  {
    id: 756,
    parentId: 750,
    name: '成本设置',
    path: '/finance/cost/settings',
    component: 'finance/cost/CostSettings',
    icon: 'icon-setting',
    type: 1,
    permission: 'finance:cost:view',
    sort: 6,
    status: 1
  },
  {
    id: 7561,
    parentId: 750,
    name: '成本中心',
    path: '/finance/cost/center',
    component: 'finance/cost/CostCenter',
    icon: 'icon-office-building',
    type: 1,
    permission: 'finance:cost:view',
    sort: 7,
    status: 1
  },
  {
    id: 7562,
    parentId: 750,
    name: '成本明细账',
    path: '/finance/cost/ledger',
    component: 'finance/cost/CostLedger',
    icon: 'icon-document',
    type: 1,
    permission: 'finance:cost:view',
    sort: 8,
    status: 1
  },
  {
    id: 757,
    parentId: 750,
    name: '盈利分析',
    path: '/finance/cost/profitability',
    component: 'finance/cost/ProfitabilityAnalysis',
    icon: 'icon-trend-charts',
    type: 1,
    permission: 'finance:cost:view',
    sort: 9,
    status: 1
  },
  {
    id: 758,
    parentId: 750,
    name: '作业成本法',
    path: '/finance/cost/abc',
    component: 'finance/cost/ActivityBasedCosting',
    icon: 'icon-data-analysis',
    type: 1,
    permission: 'finance:cost:view',
    sort: 10,
    status: 1
  },

  // 费用管理
  {
    id: 760,
    parentId: 7,
    name: '费用列表',
    path: '/finance/expenses',
    component: 'finance/expenses/Expenses',
    icon: 'icon-money',
    type: 1,
    permission: 'finance:expenses:view',
    sort: 20,
    status: 1
  },
  {
    id: 761,
    parentId: 7,
    name: '费用类型',
    path: '/finance/expenses/categories',
    component: 'finance/expenses/ExpenseCategories',
    icon: 'icon-folder',
    type: 1,
    permission: 'finance:expenses:view',
    sort: 21,
    status: 1
  },
];
