/**
 * 单据关联类型 SSOT
 * - document_links.source_type / target_type 只允许使用本文件常量
 * - 展示文案、权限映射均基于此注册表，禁止业务代码硬编码类型字符串
 */

const DOCUMENT_LINK_TYPES = Object.freeze({
  PURCHASE_REQUISITION: 'purchase_requisition',
  PURCHASE_ORDER: 'purchase_order',
  PURCHASE_RECEIPT: 'purchase_receipt',
  PURCHASE_RETURN: 'purchase_return',
  SALES_QUOTATION: 'sales_quotation',
  SALES_ORDER: 'sales_order',
  SALES_OUTBOUND: 'sales_outbound',
  SALES_RETURN: 'sales_return',
  SALES_EXCHANGE: 'sales_exchange',
  INVENTORY_INBOUND: 'inventory_inbound',
  INVENTORY_OUTBOUND: 'inventory_outbound',
  INVENTORY_TRANSFER: 'inventory_transfer',
  INVENTORY_CHECK: 'inventory_check',
  PRODUCTION_PLAN: 'production_plan',
  PRODUCTION_TASK: 'production_task',
  QUALITY_INSPECTION: 'quality_inspection',
  NONCONFORMING_PRODUCT: 'nonconforming_product',
  EIGHT_D_REPORT: 'eight_d_report',
  REWORK_TASK: 'rework_task',
  SCRAP_RECORD: 'scrap_record',
  REPLACEMENT_ORDER: 'replacement_order',
  FINANCE_VOUCHER: 'finance_voucher',
  ASSET: 'asset',
  CIP_PROJECT: 'cip_project',
  ASSET_TRANSFER: 'asset_transfer',
  ASSET_DEPRECIATION: 'asset_depreciation',
  ASSET_DISPOSAL: 'asset_disposal',
  ASSET_IMPAIRMENT: 'asset_impairment',
  AP_INVOICE: 'ap_invoice',
  AR_INVOICE: 'ar_invoice',
  TAX_INVOICE: 'tax_invoice',
  TAX_RETURN: 'tax_return',
  AP_PAYMENT: 'ap_payment',
  AR_RECEIPT: 'ar_receipt',
  BANK_TRANSFER: 'bank_transfer',
  BANK_TRANSACTION: 'bank_transaction',
  CASH_TRANSACTION: 'cash_transaction',
  OUTSOURCED_PROCESSING: 'outsourced_processing',
  OUTSOURCED_RECEIPT: 'outsourced_receipt',
  CONTRACT: 'contract',
  EXPENSE: 'expense',
  ECN: 'ecn',
  BOM: 'bom',
  MATERIAL: 'material',
});

const DOCUMENT_LINK_TYPE_LABELS = Object.freeze({
  [DOCUMENT_LINK_TYPES.PURCHASE_REQUISITION]: '采购请购单',
  [DOCUMENT_LINK_TYPES.PURCHASE_ORDER]: '采购订单',
  [DOCUMENT_LINK_TYPES.PURCHASE_RECEIPT]: '采购收货单',
  [DOCUMENT_LINK_TYPES.PURCHASE_RETURN]: '采购退货单',
  [DOCUMENT_LINK_TYPES.SALES_QUOTATION]: '销售报价单',
  [DOCUMENT_LINK_TYPES.SALES_ORDER]: '销售订单',
  [DOCUMENT_LINK_TYPES.SALES_OUTBOUND]: '销售出库单',
  [DOCUMENT_LINK_TYPES.SALES_RETURN]: '销售退货单',
  [DOCUMENT_LINK_TYPES.SALES_EXCHANGE]: '销售换货单',
  [DOCUMENT_LINK_TYPES.INVENTORY_INBOUND]: '入库单',
  [DOCUMENT_LINK_TYPES.INVENTORY_OUTBOUND]: '出库单',
  [DOCUMENT_LINK_TYPES.INVENTORY_TRANSFER]: '调拨单',
  [DOCUMENT_LINK_TYPES.INVENTORY_CHECK]: '盘点单',
  [DOCUMENT_LINK_TYPES.PRODUCTION_PLAN]: '生产计划',
  [DOCUMENT_LINK_TYPES.PRODUCTION_TASK]: '生产任务',
  [DOCUMENT_LINK_TYPES.QUALITY_INSPECTION]: '质检单',
  [DOCUMENT_LINK_TYPES.NONCONFORMING_PRODUCT]: '不合格品',
  [DOCUMENT_LINK_TYPES.EIGHT_D_REPORT]: '8D报告',
  [DOCUMENT_LINK_TYPES.REWORK_TASK]: '返工任务',
  [DOCUMENT_LINK_TYPES.SCRAP_RECORD]: '报废记录',
  [DOCUMENT_LINK_TYPES.REPLACEMENT_ORDER]: '换货单',
  [DOCUMENT_LINK_TYPES.FINANCE_VOUCHER]: '记账凭证',
  [DOCUMENT_LINK_TYPES.ASSET]: '固定资产',
  [DOCUMENT_LINK_TYPES.CIP_PROJECT]: '在建工程',
  [DOCUMENT_LINK_TYPES.ASSET_TRANSFER]: '资产调拨单',
  [DOCUMENT_LINK_TYPES.ASSET_DEPRECIATION]: '资产折旧明细',
  [DOCUMENT_LINK_TYPES.ASSET_DISPOSAL]: '资产处置单',
  [DOCUMENT_LINK_TYPES.ASSET_IMPAIRMENT]: '资产减值单',
  [DOCUMENT_LINK_TYPES.AP_INVOICE]: '应付发票',
  [DOCUMENT_LINK_TYPES.AR_INVOICE]: '应收发票',
  [DOCUMENT_LINK_TYPES.TAX_INVOICE]: '税务发票',
  [DOCUMENT_LINK_TYPES.TAX_RETURN]: '税务申报',
  [DOCUMENT_LINK_TYPES.AP_PAYMENT]: '付款单',
  [DOCUMENT_LINK_TYPES.AR_RECEIPT]: '收款单',
  [DOCUMENT_LINK_TYPES.BANK_TRANSFER]: '资金调拨单',
  [DOCUMENT_LINK_TYPES.BANK_TRANSACTION]: '银行流水',
  [DOCUMENT_LINK_TYPES.CASH_TRANSACTION]: '现金流水',
  [DOCUMENT_LINK_TYPES.OUTSOURCED_PROCESSING]: '外委加工单',
  [DOCUMENT_LINK_TYPES.OUTSOURCED_RECEIPT]: '外委加工入库单',
  [DOCUMENT_LINK_TYPES.CONTRACT]: '合同',
  [DOCUMENT_LINK_TYPES.EXPENSE]: '费用单',
  [DOCUMENT_LINK_TYPES.ECN]: '工程变更',
  [DOCUMENT_LINK_TYPES.BOM]: 'BOM',
  [DOCUMENT_LINK_TYPES.MATERIAL]: '物料',
});

const DOCUMENT_LINK_TYPE_PERMISSIONS = Object.freeze({
  [DOCUMENT_LINK_TYPES.PURCHASE_REQUISITION]: ['purchase:requisitions:view'],
  [DOCUMENT_LINK_TYPES.PURCHASE_ORDER]: ['purchase:orders:view'],
  [DOCUMENT_LINK_TYPES.PURCHASE_RECEIPT]: ['purchase:receipts:view'],
  [DOCUMENT_LINK_TYPES.PURCHASE_RETURN]: ['purchase:returns:view'],
  [DOCUMENT_LINK_TYPES.SALES_QUOTATION]: ['sales:quotations:view'],
  [DOCUMENT_LINK_TYPES.SALES_ORDER]: ['sales:orders:view'],
  [DOCUMENT_LINK_TYPES.SALES_OUTBOUND]: ['sales:outbound:view'],
  [DOCUMENT_LINK_TYPES.SALES_RETURN]: ['sales:returns:view'],
  [DOCUMENT_LINK_TYPES.SALES_EXCHANGE]: ['sales:exchanges:view', 'sales:returns:view'],
  [DOCUMENT_LINK_TYPES.INVENTORY_INBOUND]: ['inventory:inbound:view'],
  [DOCUMENT_LINK_TYPES.INVENTORY_OUTBOUND]: ['inventory:outbound:view'],
  [DOCUMENT_LINK_TYPES.INVENTORY_TRANSFER]: ['inventory:transfer:view'],
  [DOCUMENT_LINK_TYPES.INVENTORY_CHECK]: ['inventory:check:view'],
  [DOCUMENT_LINK_TYPES.PRODUCTION_PLAN]: ['production:plans:view'],
  [DOCUMENT_LINK_TYPES.PRODUCTION_TASK]: ['production:tasks:view'],
  [DOCUMENT_LINK_TYPES.QUALITY_INSPECTION]: ['quality:inspections:view'],
  [DOCUMENT_LINK_TYPES.NONCONFORMING_PRODUCT]: ['quality:nonconforming:view'],
  [DOCUMENT_LINK_TYPES.EIGHT_D_REPORT]: ['quality:8d:view'],
  [DOCUMENT_LINK_TYPES.REWORK_TASK]: ['quality:rework:view'],
  [DOCUMENT_LINK_TYPES.SCRAP_RECORD]: ['quality:scrap:view'],
  [DOCUMENT_LINK_TYPES.REPLACEMENT_ORDER]: ['quality:replacement:view'],
  [DOCUMENT_LINK_TYPES.FINANCE_VOUCHER]: ['finance:entries:view'],
  [DOCUMENT_LINK_TYPES.ASSET]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.CIP_PROJECT]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.ASSET_TRANSFER]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.ASSET_DEPRECIATION]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.ASSET_DISPOSAL]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.ASSET_IMPAIRMENT]: ['finance:assets:view'],
  [DOCUMENT_LINK_TYPES.AP_INVOICE]: ['finance:ap:view'],
  [DOCUMENT_LINK_TYPES.AR_INVOICE]: ['finance:ar:view'],
  [DOCUMENT_LINK_TYPES.TAX_INVOICE]: ['finance:tax:view'],
  [DOCUMENT_LINK_TYPES.TAX_RETURN]: ['finance:tax:view'],
  [DOCUMENT_LINK_TYPES.AP_PAYMENT]: ['finance:ap:view'],
  [DOCUMENT_LINK_TYPES.AR_RECEIPT]: ['finance:ar:view'],
  [DOCUMENT_LINK_TYPES.BANK_TRANSFER]: ['finance:cash:view'],
  [DOCUMENT_LINK_TYPES.BANK_TRANSACTION]: ['finance:cash:view'],
  [DOCUMENT_LINK_TYPES.CASH_TRANSACTION]: ['finance:cash:view'],
  [DOCUMENT_LINK_TYPES.OUTSOURCED_PROCESSING]: ['purchase:processing:view'],
  [DOCUMENT_LINK_TYPES.OUTSOURCED_RECEIPT]: ['purchase:processing-receipts:view'],
  [DOCUMENT_LINK_TYPES.CONTRACT]: ['contract:view'],
  [DOCUMENT_LINK_TYPES.EXPENSE]: ['finance:expenses:view'],
  [DOCUMENT_LINK_TYPES.ECN]: ['basedata:ecn:view'],
  [DOCUMENT_LINK_TYPES.BOM]: ['basedata:boms:view'],
  [DOCUMENT_LINK_TYPES.MATERIAL]: ['basedata:materials:view'],
});

/**
 * 库存单据 reference_type → 链路类型
 * 仅登记合法业务引用，未知类型返回 null（不写脏 link）
 */
const INVENTORY_REFERENCE_TO_LINK_TYPE = Object.freeze({
  production_task: DOCUMENT_LINK_TYPES.PRODUCTION_TASK,
  production: DOCUMENT_LINK_TYPES.PRODUCTION_TASK,
  production_plan: DOCUMENT_LINK_TYPES.PRODUCTION_PLAN,
  sales_order: DOCUMENT_LINK_TYPES.SALES_ORDER,
  sales_outbound: DOCUMENT_LINK_TYPES.SALES_OUTBOUND,
  purchase_order: DOCUMENT_LINK_TYPES.PURCHASE_ORDER,
  purchase_receipt: DOCUMENT_LINK_TYPES.PURCHASE_RECEIPT,
  quality_inspection: DOCUMENT_LINK_TYPES.QUALITY_INSPECTION,
  outsourced_processing: DOCUMENT_LINK_TYPES.OUTSOURCED_PROCESSING,
  outsourced_receipt: DOCUMENT_LINK_TYPES.OUTSOURCED_RECEIPT,
});

function resolveInventoryReferenceLinkType(referenceType) {
  if (referenceType === null || referenceType === undefined || referenceType === '') return null;
  const key = String(referenceType).trim();
  return INVENTORY_REFERENCE_TO_LINK_TYPE[key] || null;
}

function isKnownDocumentLinkType(type) {
  return Object.prototype.hasOwnProperty.call(DOCUMENT_LINK_TYPE_LABELS, String(type || ''));
}

module.exports = {
  DOCUMENT_LINK_TYPES,
  DOCUMENT_LINK_TYPE_LABELS,
  DOCUMENT_LINK_TYPE_PERMISSIONS,
  INVENTORY_REFERENCE_TO_LINK_TYPE,
  resolveInventoryReferenceLinkType,
  isKnownDocumentLinkType,
};
